### ISSUE TITLE
STOLEN CODE

### ISSUE THREAD

**Issue by rafalbuj** [nycto-hackerone/Nycto-Host#1]
Fucking loser stealing my shit. You're a loser that doesn't know shit.

**Comment by rafalbuj** [comment]
All you do is steal people's code. You couldn't code a "Hello world" script if you Googled it.

**Comment by rafalbuj** [comment]
I could write a code into your wife's panties.

**Comment by nycto-hackerone** [comment]
Lmfao Stole your code? no lil boy you added code to my code and went around facebook claiming it was your's ... all you did was add the damn scrolling font code to it lulz... then you wanna act like a 1337 h4ck3r by sending people links and claiming you're going to teach them hacking and you hack them or try to hack them lol.. i bet you can't hack your way out a wet paper bag... if you tried ...
