### ISSUE TITLE
CODE THIEF!!!

### ISSUE THREAD

**Issue by hashbrown1013** [nycto-hackerone/Nycto-Host#2]
ARGOLES MILLER (nycto-hackerone) WILL STEAL ALL OF YOUR HARD WORK AND PUT HIS NAME ON IT!!!!!

**Comment by rafalbuj** [comment]
He's an inept retard. All he does is steal code from Github and call it his own.

**Comment by nycto-hackerone** [comment]
lulz the funny thing is that was my script he just added a scrolling font code to it ... fucker poser ass lil script kiddie bitch boy and claims he can hack lmao all ive seen him hack is fake accounts XD XD on facebook ............

**Comment by nycto-hackerone** [comment]
mad cause i blocked his fake ass on facebook lmao... he's a fucking retard ... i'll call that bitch out any time and day.... " FAKE ASS MOTHER FUCKIN WANNA BE HACKER" SO fake you can't even call him a fucking NOOB.... / even his lil buddies on his groups call him fake /
